name: Pages

on:
  push:
    branches:
      - main # default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: true
    - name: Build and Deploy
      uses: renzhaosy/hexo-deploy-action@master
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_REPOSITORY: jiachuanH/jiachuanh.github.io # The repository the action should deploy to.
        BRANCH: gh-pages  # The branch the action should deploy to.
        PUBLISH_DIR: ./public # The folder the action should deploy.
